### PR TITLE
Added low-pro cpu time to run

### PR DESCRIPTION
**Pull request by tukoz**
Adding low-pro cpu runtime.

### CODE REVIEW

**Comment by pid1** [comment]
I appreciate the time estimates for lower-end hardware, but I am confused by your format. What do the `1`, `~22'`, and `~1` represent?

**Comment by tukoz** [comment]
Means the runtime, eg:

```
+ffmpeg: On an i5-4440@3.1GHz, ~3 minutes per run, 20 minutes total (respectively ~1hour, 8 hours on an atom n450) 
```

yeah as low-pro pro boxes mayhave other task to run, and/or be m0ved, it should help owners to schedule the test.

**Comment by pid1** [comment]
Fixed in ef240a9. Thanks!

**Comment by tukoz** [comment]
Owdy, nice :+1:

**Pull request closed without merging**
